### ISSUE TITLE
layerindex needs LAYERRECOMMENDS for meta-intel

### ISSUE THREAD

**Issue by moto-timo** [zboszor/meta-clang-revival#1]
When dynamic layers are set, recipes cannot be parsed by layerindex and will fail. I manually added meta-intel in the Edit Layer form, but this then [results in](https://layers.openembedded.org/layerindex/updates/40862/)

`WARNING: Dependencies "<QuerySet [<LayerDependency: meta-clang-revival depends on meta-intel>]>" are not in meta-clang-revival's conf/layer.conf
WARNING: Either set REMOVE_LAYER_DEPENDENCIES to remove them from the database, or fix conf/layer.conf`

So you need to add the following to `layer.conf`
`LAYERRECOMMENDS_clang-revival-layer = "intel"`

**Comment by zboszor** [comment]
@moto-timo Thank you!
